/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of Channel.xs. Do not edit this file, edit Channel.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Channel.xs"
#include "module.h"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 16 "Channel.c"
XS(XS_Ekg2__Irc__Channel_part); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__Channel_part)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::Channel::part(chan, reason)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Irc__Channel	chan = (channel_t *) Ekg2_ref_object(ST(0));
	char *	reason = (char *)SvPV_nolen(ST(1));
#line 10 "Channel.xs"
	debug("PART: %s %s\n", chan->name, reason);
#line 29 "Channel.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2__Irc__Channel); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2__Irc__Channel)
{
    dXSARGS;
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Ekg2::Irc::Channel::part", XS_Ekg2__Irc__Channel_part, file, "$$");
    XSRETURN_YES;
}

