/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of Irc.xs. Do not edit this file, edit Irc.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Irc.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Irc.c"
#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2__Irc); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2__Irc)
{
    dXSARGS;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;


    /* Initialisation Section */

#line 11 "Irc.xs"
	ekg2_boot(Irc__Server);
	ekg2_boot(Irc__Channel);
	ekg2_boot(Irc__User);

#line 38 "Irc.c"

    /* End of Initialisation Section */

    XSRETURN_YES;
}

