/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of Server.xs. Do not edit this file, edit Server.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Server.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Server.c"
XS(XS_Ekg2__Irc_servers); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc_servers)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::servers()");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 8 "Server.xs"
        list_t l;
#line 30 "Server.c"
#line 10 "Server.xs"
        for (l = sessions; l; l = l->next) {
		if (!xstrncasecmp( session_uid_get( (session_t *) l->data), IRC4, 4)) {
            		XPUSHs(sv_2mortal(bless_server( (session_t *) l->data)));
		}
        }
#line 37 "Server.c"
	PUTBACK;
	return;
    }
}

XS(XS_Ekg2__Irc__Server_raw); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__Server_raw)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::Server::raw(s, str)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Session	s = (session_t *) Ekg2_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));
#line 21 "Server.xs"
	if (!xstrncasecmp( session_uid_get( (session_t *) s), IRC4, 4)) irc_write(irc_private(s), "%s\r\n", str);
#line 55 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Irc__Server_quit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__Server_quit)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::Server::quit(s, quitreason)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Session	s = (session_t *) Ekg2_ref_object(ST(0));
	char *	quitreason = (char *)SvPV_nolen(ST(1));
#line 25 "Server.xs"
	if (!xstrncasecmp( session_uid_get( (session_t *) s), IRC4, 4)) irc_write(irc_private(s), "QUIT :%s\r\n", quitreason);
#line 72 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Irc__Server_newnick); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__Server_newnick)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::Server::newnick(s, newnick)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Session	s = (session_t *) Ekg2_ref_object(ST(0));
	char *	newnick = (char *)SvPV_nolen(ST(1));
#line 29 "Server.xs"
	if (!xstrncasecmp( session_uid_get( (session_t *) s), IRC4, 4)) irc_write(irc_private(s), "NICK %s\r\n", newnick);
#line 89 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Irc__Server_setmode); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__Server_setmode)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::Server::setmode(s, mode)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Session	s = (session_t *) Ekg2_ref_object(ST(0));
	char *	mode = (char *)SvPV_nolen(ST(1));
#line 33 "Server.xs"
	if (!xstrncasecmp( session_uid_get( (session_t *) s), IRC4, 4)) irc_write(irc_private(s), "MODE %s %s\r\n", irc_private(s)->nick, mode);
#line 106 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Irc__Server_oper); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__Server_oper)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::Server::oper(s, nick, password)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Session	s = (session_t *) Ekg2_ref_object(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	char *	password = (char *)SvPV_nolen(ST(2));
#line 37 "Server.xs"
	if (!xstrncasecmp( session_uid_get( (session_t *) s), IRC4, 4)) irc_write(irc_private(s), "OPER %s %s\r\n", nick, password);
#line 124 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Irc__Server_die); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__Server_die)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::Server::die(s, reason)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Session	s = (session_t *) Ekg2_ref_object(ST(0));
	char *	reason = (char *)SvPV_nolen(ST(1));
#line 41 "Server.xs"
	if (!xstrncasecmp( session_uid_get( (session_t *) s), IRC4, 4)) irc_write(irc_private(s), "DIE %s\r\n", reason);
#line 141 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Irc__Server_channels); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__Server_channels)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::Server::channels(s)");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 45 "Server.xs"
	list_t l;
#line 158 "Server.c"
	Ekg2__Session	s = (session_t *) Ekg2_ref_object(ST(0));
#line 47 "Server.xs"
	if (!xstrncasecmp( session_uid_get( (session_t *) s), IRC4, 4)) {
    		for (l = irc_private(s)->channels; l; l = l->next) {
            		XPUSHs(sv_2mortal(bless_channel( (channel_t *) l->data)));
	        }
	}
#line 166 "Server.c"
	PUTBACK;
	return;
    }
}

XS(XS_Ekg2__Irc__Server_people); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__Server_people)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::Server::people(s)");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 55 "Server.xs"
        list_t l;
#line 184 "Server.c"
	Ekg2__Session	s = (session_t *) Ekg2_ref_object(ST(0));
#line 57 "Server.xs"
        if (!xstrncasecmp( session_uid_get( (session_t *) s), IRC4, 4)) {
                for (l = irc_private(s)->people; l; l = l->next) {
                        XPUSHs(sv_2mortal(bless_person( (people_t *) l->data)));
                }
        }
#line 192 "Server.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2__Irc__Server); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2__Irc__Server)
{
    dXSARGS;
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Ekg2::Irc::servers", XS_Ekg2__Irc_servers, file, "");
        newXSproto("Ekg2::Irc::Server::raw", XS_Ekg2__Irc__Server_raw, file, "$$");
        newXSproto("Ekg2::Irc::Server::quit", XS_Ekg2__Irc__Server_quit, file, "$$");
        newXSproto("Ekg2::Irc::Server::newnick", XS_Ekg2__Irc__Server_newnick, file, "$$");
        newXSproto("Ekg2::Irc::Server::setmode", XS_Ekg2__Irc__Server_setmode, file, "$$");
        newXSproto("Ekg2::Irc::Server::oper", XS_Ekg2__Irc__Server_oper, file, "$$$");
        newXSproto("Ekg2::Irc::Server::die", XS_Ekg2__Irc__Server_die, file, "$$");
        newXSproto("Ekg2::Irc::Server::channels", XS_Ekg2__Irc__Server_channels, file, "$");
        newXSproto("Ekg2::Irc::Server::people", XS_Ekg2__Irc__Server_people, file, "$");
    XSRETURN_YES;
}

