/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of User.xs. Do not edit this file, edit User.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "User.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "User.c"
XS(XS_Ekg2__Irc__User_channels); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__User_channels)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::User::channels(user)");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 11 "User.xs"
        list_t l;
#line 30 "User.c"
	Ekg2__Irc__User	user = (people_t *) Ekg2_ref_object(ST(0));
#line 13 "User.xs"
        for (l = user->channels ; l; l = l->next) {
                XPUSHs(sv_2mortal(bless_channperson( (people_chan_t *) l->data)));
        }
#line 36 "User.c"
	PUTBACK;
	return;
    }
}

XS(XS_Ekg2__Irc__User_kill); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Irc__User_kill)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Irc::User::kill(user, reason)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Irc__User	user = (people_t *) Ekg2_ref_object(ST(0));
	char *	reason = (char *)SvPV_nolen(ST(1));
#line 20 "User.xs"
	debug("KILL %s :%s\n", user->nick+4, reason);
#line 54 "User.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2__Irc__User); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2__Irc__User)
{
    dXSARGS;
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Ekg2::Irc::User::channels", XS_Ekg2__Irc__User_channels, file, "$");
        newXSproto("Ekg2::Irc::User::kill", XS_Ekg2__Irc__User_kill, file, "$$");
    XSRETURN_YES;
}

