
Import('*')

sslbackends = ['gnutls', 'openssl']

try:
	opts
except NameError:
	pass
else:
	props = [['list', 'SSL', 'SSL implementation to use with jabber plugin', sslbackends]]
	Return('props')

try:
	defines
except NameError:
	pass
else:
	for o in sslbackends:
		if o in optdeps:
			defines['JABBER_HAVE_%s' % o.upper()] = True
			break

try:
	env
except NameError:
	pass
else:
	plugin	= {
		'type':			'protocol',
		'state':		'stable',
		'depends':		['expat'],
		'optdepends':	['@SSL', 'zlib']
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
