
Import('*')

sslbackends = ['gnutls', 'openssl']

try:
	opts.Add(EnumOption('JABBER_SSL', 'SSL implementation to use with jabber plugin', 'both', sslbackends + ['both', 'none']))
except NameError:
	pass

try:
	jssl = env['JABBER_SSL']
except NameError:
	pass
else:
	ssldeps = []
	for o in sslbackends:
		if jssl == o or jssl == 'both':
			ssldeps.append(o)

	plugin	= {
		'type':			'protocol',
		'state':		'stable',
		'depends':		['expat'],
		'optdepends':	[ssldeps, 'zlib']
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
