
Import('*')

try:
	env	# stage 2
	plugin	= {
		'type':			'scripting',
		'state':		'experimental',
		'depends':		['ruby']
		}

	Return('plugin')
except NameError:
	pass

# vim:ts=4:sts=4:sw=4:syntax=python
