
Import('*')

try:
	env	# stage 2
	plugin	= {
		'type':			'protocol',
		'state':		'unstable',
		'depends':		[],
		'optdepends':	['expat']
		}

	Return('plugin')
except NameError:
	pass

# vim:ts=4:sts=4:sw=4:syntax=python
