
Import('*')

if 'env' in globals():
	plugin	= {
		'type':			'ui',
		'state':		'stable',
		'depends':		['ncurses'],
		'optdepends':	['gpm', 'aspell']
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
