/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of Command.xs. Do not edit this file, edit Command.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Command.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Command.c"
XS(XS_Ekg2_commands); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_commands)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::commands()");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 8 "Command.xs"
        list_t l;
#line 30 "Command.c"
#line 10 "Command.xs"
        for (l = commands; l; l = l->next) {
                XPUSHs(sv_2mortal(bless_command( (command_t *) l->data)));
        }
#line 35 "Command.c"
	PUTBACK;
	return;
    }
}

XS(XS_Ekg2__Command_execute); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Command_execute)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Command::execute(comm, param)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Command	comm = (command_t *) Ekg2_ref_object(ST(0));
	char *	param = (char *)SvPV_nolen(ST(1));
#line 21 "Command.xs"
	char *tmp = saprintf("%s %s", comm->name, param);
        command_exec(NULL, NULL, comm->name, 0);
	xfree(tmp);
#line 55 "Command.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2__Command); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2__Command)
{
    dXSARGS;
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Ekg2::commands", XS_Ekg2_commands, file, "");
        newXSproto("Ekg2::Command::execute", XS_Ekg2__Command_execute, file, "$$");
    XSRETURN_YES;
}

