/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of Ekg2.xs. Do not edit this file, edit Ekg2.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Ekg2.xs"
#include "module.h"

static int initialized = 0;
#define VAR_PREFIX ""

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 20 "Ekg2.c"
XS(XS_Ekg2_echo); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_echo)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::echo(str)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	str = (char *)SvPV_nolen(ST(0));
#line 14 "Ekg2.xs"
	char *skrypt = SvPV(perl_eval_pv("caller", TRUE), PL_na)+14;
	print("script_generic", "perl", skrypt, str);
#line 33 "Ekg2.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2_debug); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_debug)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::debug(debstr)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	debstr = (char *)SvPV_nolen(ST(0));
#line 19 "Ekg2.xs"
	debug("(perldebug) %s", debstr);
#line 49 "Ekg2.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_init)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::init()");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 23 "Ekg2.xs"
	initialized = 1;
#line 64 "Ekg2.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2_deinit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_deinit)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::deinit()");
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 26 "Ekg2.xs"
#line 78 "Ekg2.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2_timer_bind); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_timer_bind)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::timer_bind(freq, handler)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	int	freq = (int)SvIV(ST(0));
	char *	handler = (char *)SvPV_nolen(ST(1));
#line 32 "Ekg2.xs"
	perl_timer_bind(freq, handler);
#line 97 "Ekg2.c"
    }
    XSRETURN(1);
}

XS(XS_Ekg2_timer_unbind); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_timer_unbind)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::timer_unbind(scr_time)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	void *	scr_time = INT2PTR(void *,SvIV(ST(0)));
#line 36 "Ekg2.xs"
//	debug("%d\n", scr_time);
	perl_timer_unbind(scr_time);
#line 116 "Ekg2.c"
    }
    XSRETURN(1);
}

XS(XS_Ekg2_command_bind); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_command_bind)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::command_bind(command, handler)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	char *	command = (char *)SvPV_nolen(ST(0));
	char *	handler = (char *)SvPV_nolen(ST(1));
#line 43 "Ekg2.xs"
	perl_command_bind(command, handler);
#line 135 "Ekg2.c"
    }
    XSRETURN(1);
}

XS(XS_Ekg2_handler_bind); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_handler_bind)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::handler_bind(query_name, handler)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	char *	query_name = (char *)SvPV_nolen(ST(0));
	char *	handler = (char *)SvPV_nolen(ST(1));
#line 49 "Ekg2.xs"
	perl_handler_bind(query_name, handler);
#line 154 "Ekg2.c"
    }
    XSRETURN(1);
}

XS(XS_Ekg2_var_add_handler); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_var_add_handler)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Ekg2::var_add_handler(name, value, handler)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Variable	RETVAL;
	char *	name = (char *)SvPV_nolen(ST(0));
	char *	value = (char *)SvPV_nolen(ST(1));
	char *	handler = (char *)SvPV_nolen(ST(2));
#line 55 "Ekg2.xs"
	char *temp = saprintf("%s%s", VAR_PREFIX, name);
	perl_variable_add(temp, value, handler);
	xfree(temp);
#line 175 "Ekg2.c"
    }
    XSRETURN(1);
}

XS(XS_Ekg2_var_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_var_add)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::var_add(name, value)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Variable	RETVAL;
	char *	name = (char *)SvPV_nolen(ST(0));
	char *	value = (char *)SvPV_nolen(ST(1));
#line 61 "Ekg2.xs"
	char *temp = saprintf("%s%s", VAR_PREFIX,name);
	perl_variable_add(temp, value, NULL);
	xfree(temp);
#line 195 "Ekg2.c"
    }
    XSRETURN(1);
}

XS(XS_Ekg2_var_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_var_find)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::var_find(name)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Variable	RETVAL;
	char *	name = (char *)SvPV_nolen(ST(0));
#line 67 "Ekg2.xs"
	char *temp = saprintf("%s%s", VAR_PREFIX,name);
//	RETVAL = (script_var_find(NULL, name)) ->var;
	RETVAL = variable_find(temp);
	xfree(temp);
#line 215 "Ekg2.c"
	ST(0) = (void *) bless_variable( (variable_t *) RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Ekg2_EKG_MSGCLASS_SENT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_EKG_MSGCLASS_SENT)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::EKG_MSGCLASS_SENT()");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 78 "Ekg2.xs"
	RETVAL = EKG_MSGCLASS_SENT;
#line 235 "Ekg2.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ekg2_EKG_MSGCLASS_SENT_CHAT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_EKG_MSGCLASS_SENT_CHAT)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::EKG_MSGCLASS_SENT_CHAT()");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 84 "Ekg2.xs"
	RETVAL = EKG_MSGCLASS_SENT_CHAT;
#line 253 "Ekg2.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ekg2_EKG_NO_THEMEBIT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_EKG_NO_THEMEBIT)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::EKG_NO_THEMEBIT()");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 90 "Ekg2.xs"
        RETVAL = EKG_NO_THEMEBIT;
#line 271 "Ekg2.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2)
{
    dXSARGS;
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Ekg2::echo", XS_Ekg2_echo, file, "$");
        newXSproto("Ekg2::debug", XS_Ekg2_debug, file, "$");
        newXSproto("Ekg2::init", XS_Ekg2_init, file, "");
        newXSproto("Ekg2::deinit", XS_Ekg2_deinit, file, "");
        newXSproto("Ekg2::timer_bind", XS_Ekg2_timer_bind, file, "$$");
        newXSproto("Ekg2::timer_unbind", XS_Ekg2_timer_unbind, file, "$");
        newXSproto("Ekg2::command_bind", XS_Ekg2_command_bind, file, "$$");
        newXSproto("Ekg2::handler_bind", XS_Ekg2_handler_bind, file, "$$");
        newXSproto("Ekg2::var_add_handler", XS_Ekg2_var_add_handler, file, "$$$");
        newXSproto("Ekg2::var_add", XS_Ekg2_var_add, file, "$$");
        newXSproto("Ekg2::var_find", XS_Ekg2_var_find, file, "$");
        newXSproto("Ekg2::EKG_MSGCLASS_SENT", XS_Ekg2_EKG_MSGCLASS_SENT, file, "");
        newXSproto("Ekg2::EKG_MSGCLASS_SENT_CHAT", XS_Ekg2_EKG_MSGCLASS_SENT_CHAT, file, "");
        newXSproto("Ekg2::EKG_NO_THEMEBIT", XS_Ekg2_EKG_NO_THEMEBIT, file, "");

    /* Initialisation Section */

#line 98 "Ekg2.xs"
	ekg2_boot(Session);
	ekg2_boot(Variable);
	ekg2_boot(Plugin);
	ekg2_boot(Window);
	ekg2_boot(Command);
	ekg2_boot(Timer);
	ekg2_boot(Userlist);

#line 316 "Ekg2.c"

    /* End of Initialisation Section */

    XSRETURN_YES;
}

