/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of Plugin.xs. Do not edit this file, edit Plugin.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Plugin.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Plugin.c"
XS(XS_Ekg2_plugin_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_plugin_find)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::plugin_find(name)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Plugin	RETVAL;
	const char *	name = (const char *)SvPV_nolen(ST(0));

	RETVAL = plugin_find(name);
	ST(0) = (void *) bless_plugin( (plugin_t *) RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Ekg2_plugins); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_plugins)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::plugins()");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 10 "Plugin.xs"
        list_t l;
#line 49 "Plugin.c"
#line 12 "Plugin.xs"
        for (l = plugins; l; l = l->next) {
                XPUSHs(sv_2mortal(bless_plugin( (plugin_t *) l->data)));
        }
#line 54 "Plugin.c"
	PUTBACK;
	return;
    }
}

XS(XS_Ekg2_plugin_load); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_plugin_load)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::plugin_load(name)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	const char *	name = (const char *)SvPV_nolen(ST(0));
#line 18 "Plugin.xs"
	RETVAL = plugin_load(name, -254, 1);
#line 73 "Plugin.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ekg2__Plugin_unload); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Plugin_unload)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Plugin::unload(plugin)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	Ekg2__Plugin	plugin = (plugin_t *) Ekg2_ref_object(ST(0));

	RETVAL = plugin_unload(plugin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2__Plugin); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2__Plugin)
{
    dXSARGS;
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Ekg2::plugin_find", XS_Ekg2_plugin_find, file, "$");
        newXSproto("Ekg2::plugins", XS_Ekg2_plugins, file, "");
        newXSproto("Ekg2::plugin_load", XS_Ekg2_plugin_load, file, "$");
        newXSproto("Ekg2::Plugin::unload", XS_Ekg2__Plugin_unload, file, "$");
    XSRETURN_YES;
}

