/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of Session.xs. Do not edit this file, edit Session.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Session.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Session.c"
XS(XS_Ekg2_sessions); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_sessions)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::sessions()");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 8 "Session.xs"
        list_t l;
#line 30 "Session.c"
#line 10 "Session.xs"
        for (l = sessions; l; l = l->next) {
                XPUSHs(sv_2mortal(bless_session( (session_t *) l->data)));
        }
#line 35 "Session.c"
	PUTBACK;
	return;
    }
}

XS(XS_Ekg2_session_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_session_find)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::session_find(uid)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Session	RETVAL;
	const char *	uid = (const char *)SvPV_nolen(ST(0));

	RETVAL = session_find(uid);
	ST(0) = (void *) bless_session( (session_t *) RETVAL);
	
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Ekg2_session_current); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_session_current)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::session_current()");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Session	RETVAL;
#line 19 "Session.xs"
	RETVAL = session_current;
#line 71 "Session.c"
	ST(0) = (void *) bless_session( (session_t *) RETVAL);
	
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Ekg2__Session__Param_session_help); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Session__Param_session_help)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Session::Param::session_help(session, name)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Session	session = (session_t *) Ekg2_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));

	session_help(session, name);
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Session__Param_help); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Session__Param_help)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Session::Param::help(param, session)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Session__Param	param = (session_param_t *) Ekg2_ref_object(ST(0));
	Ekg2__Session	session = (session_t *) Ekg2_ref_object(ST(1));
#line 32 "Session.xs"
	session_help(session, param->key);
#line 107 "Session.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Session__Param_set); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Session__Param_set)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Ekg2::Session::Param::set(param, session, value)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	Ekg2__Session__Param	param = (session_param_t *) Ekg2_ref_object(ST(0));
	Ekg2__Session	session = (session_t *) Ekg2_ref_object(ST(1));
	const char *	value = (const char *)SvPV_nolen(ST(2));
#line 36 "Session.xs"
	session_set(session, param->key, value);
#line 127 "Session.c"
    }
    XSRETURN(1);
}

XS(XS_Ekg2__Session_params); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Session_params)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Session::params(session)");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 47 "Session.xs"
        list_t l;
#line 144 "Session.c"
	Ekg2__Session	session = (session_t *) Ekg2_ref_object(ST(0));
#line 49 "Session.xs"
        for (l = session->params; l; l = l->next) {
                XPUSHs(sv_2mortal(bless_session_param( (session_param_t *) l->data)));
        }
#line 150 "Session.c"
	PUTBACK;
	return;
    }
}

XS(XS_Ekg2__Session_disconnect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Session_disconnect)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Session::disconnect(session)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	Ekg2__Session	session = (session_t *) Ekg2_ref_object(ST(0));
#line 56 "Session.xs"
	RETVAL = command_exec(NULL, session, "/disconnect", 0);
#line 169 "Session.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ekg2__Session_connect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Session_connect)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Session::connect(session)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	Ekg2__Session	session = (session_t *) Ekg2_ref_object(ST(0));
#line 62 "Session.xs"
	RETVAL = command_exec(NULL, session, "/connect", 0);
#line 188 "Session.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2__Session); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2__Session)
{
    dXSARGS;
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Ekg2::sessions", XS_Ekg2_sessions, file, "");
        newXSproto("Ekg2::session_find", XS_Ekg2_session_find, file, "$");
        newXSproto("Ekg2::session_current", XS_Ekg2_session_current, file, "");
        newXSproto("Ekg2::Session::Param::session_help", XS_Ekg2__Session__Param_session_help, file, "$$");
        newXSproto("Ekg2::Session::Param::help", XS_Ekg2__Session__Param_help, file, "$$");
        newXSproto("Ekg2::Session::Param::set", XS_Ekg2__Session__Param_set, file, "$$$");
        newXSproto("Ekg2::Session::params", XS_Ekg2__Session_params, file, "$");
        newXSproto("Ekg2::Session::disconnect", XS_Ekg2__Session_disconnect, file, "$");
        newXSproto("Ekg2::Session::connect", XS_Ekg2__Session_connect, file, "$");
    XSRETURN_YES;
}

