/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of Timer.xs. Do not edit this file, edit Timer.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Timer.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Timer.c"
XS(XS_Ekg2_timers); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_timers)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::timers()");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 8 "Timer.xs"
        list_t l;
#line 30 "Timer.c"
#line 10 "Timer.xs"
        for (l = timers; l; l = l->next) {
                XPUSHs(sv_2mortal(bless_timer( (struct timer *) l->data)));
        }
#line 35 "Timer.c"
	PUTBACK;
	return;
    }
}

XS(XS_Ekg2__Timer_delete); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Timer_delete)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Timer::delete(timer)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	Ekg2__PTimer	timer = (list_t ) INT2PTR(void *,SvIV(ST(0)));
#line 22 "Timer.xs"
	timer_remove(timer->plugin, timer->name);
#line 54 "Timer.c"
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2__Timer); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2__Timer)
{
    dXSARGS;
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Ekg2::timers", XS_Ekg2_timers, file, "");
        newXSproto("Ekg2::Timer::delete", XS_Ekg2__Timer_delete, file, "$");
    XSRETURN_YES;
}

