/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of Userlist.xs. Do not edit this file, edit Userlist.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Userlist.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Userlist.c"
XS(XS_Ekg2__User__userlist_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__User__userlist_remove)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::User::_userlist_remove(session, u)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	Ekg2__Session	session = (session_t *) Ekg2_ref_object(ST(0));
	Ekg2__User	u = (userlist_t *) Ekg2_ref_object(ST(1));

	RETVAL = _userlist_remove(session, u);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ekg2__User__userlist_remove_u); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__User__userlist_remove_u)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::User::_userlist_remove_u(userlist, u)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	Ekg2__Userlist	userlist = (list_t ) INT2PTR(void *,SvIV(ST(0)));
	Ekg2__User	u = (userlist_t *) Ekg2_ref_object(ST(1));

	RETVAL = _userlist_remove_u(userlist, u);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ekg2__Userlist_users); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Userlist_users)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Userlist::users(userlist)");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 21 "Userlist.xs"
        list_t l;
#line 68 "Userlist.c"
	void *	userlist = INT2PTR(void *,SvIV(ST(0)));
#line 23 "Userlist.xs"
        for (l = userlist ; l; l = l->next) {
                XPUSHs(sv_2mortal(bless_user( (userlist_t *) l->data)));
        }
#line 74 "Userlist.c"
	PUTBACK;
	return;
    }
}

XS(XS_Ekg2__Userlist_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Userlist_add)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Ekg2::Userlist::add(session, uid, nickname)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	Ekg2__Session	session = (session_t *) Ekg2_ref_object(ST(0));
	const char *	uid = (const char *)SvPV_nolen(ST(1));
	const char *	nickname = (const char *)SvPV_nolen(ST(2));

	RETVAL = userlist_add(session, uid, nickname);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2__Userlist); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2__Userlist)
{
    dXSARGS;
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Ekg2::User::_userlist_remove", XS_Ekg2__User__userlist_remove, file, "$$");
        newXSproto("Ekg2::User::_userlist_remove_u", XS_Ekg2__User__userlist_remove_u, file, "$$");
        newXSproto("Ekg2::Userlist::users", XS_Ekg2__Userlist_users, file, "$");
        newXSproto("Ekg2::Userlist::add", XS_Ekg2__Userlist_add, file, "$$$");
    XSRETURN_YES;
}

