/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.08 from the
 * contents of Window.xs. Do not edit this file, edit Window.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Window.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Window.c"
XS(XS_Ekg2_window_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_window_find)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::window_find(target)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Window	RETVAL;
	const char *	target = (const char *)SvPV_nolen(ST(0));

	RETVAL = window_find(target);
	ST(0) = (void *) bless_window( (window_t *) RETVAL);
	
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Ekg2_window_current); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_window_current)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::window_current()");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Window	RETVAL;
#line 12 "Window.xs"
        RETVAL = window_current;
#line 48 "Window.c"
	ST(0) = (void *) bless_window( (window_t *) RETVAL);
	
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Ekg2_windows); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2_windows)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::windows()");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 20 "Window.xs"
        list_t l;
#line 68 "Window.c"
#line 22 "Window.xs"
        for (l = windows; l; l = l->next) {
                XPUSHs(sv_2mortal(bless_window( (window_t *) l->data)));
        }
#line 73 "Window.c"
	PUTBACK;
	return;
    }
}

XS(XS_Ekg2__Window_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Window_next)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Ekg2::Window::next()");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	window_next();
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Window_print); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Window_print)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Ekg2::Window::print(wind, line)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Window	wind = (window_t *) Ekg2_ref_object(ST(0));
	char *	line = (char *)SvPV_nolen(ST(1));
#line 34 "Window.xs"
	print_window(wind->target, wind->session, 0, "generic", line);
#line 105 "Window.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Window_switch); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Window_switch)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Window::switch(wind)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Window	wind = (window_t *) Ekg2_ref_object(ST(0));
#line 40 "Window.xs"
	window_switch(wind->id);
#line 121 "Window.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Window_switch_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Window_switch_id)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Window::switch_id(id)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	id = (int)SvIV(ST(0));
#line 44 "Window.xs"
	window_switch(id);
#line 137 "Window.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Window_kill); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Window_kill)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Window::kill(wind)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Window	wind = (window_t *) Ekg2_ref_object(ST(0));
#line 50 "Window.xs"
	window_kill(wind, 0);
#line 153 "Window.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Ekg2__Window_exists); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ekg2__Window_exists)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Ekg2::Window::exists(id)");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Ekg2__Window	RETVAL;
	int	id = (int)SvIV(ST(0));

	RETVAL = window_exists(id);
	ST(0) = (void *) bless_window( (window_t *) RETVAL);
	
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ekg2__Window); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ekg2__Window)
{
    dXSARGS;
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Ekg2::window_find", XS_Ekg2_window_find, file, "$");
        newXSproto("Ekg2::window_current", XS_Ekg2_window_current, file, "");
        newXSproto("Ekg2::windows", XS_Ekg2_windows, file, "");
        newXSproto("Ekg2::Window::next", XS_Ekg2__Window_next, file, "");
        newXSproto("Ekg2::Window::print", XS_Ekg2__Window_print, file, "$$");
        newXSproto("Ekg2::Window::switch", XS_Ekg2__Window_switch, file, "$");
        newXSproto("Ekg2::Window::switch_id", XS_Ekg2__Window_switch_id, file, "$");
        newXSproto("Ekg2::Window::kill", XS_Ekg2__Window_kill, file, "$");
        newXSproto("Ekg2::Window::exists", XS_Ekg2__Window_exists, file, "$");
    XSRETURN_YES;
}

