
Import('*')

sqlvers = ['sqlite', 'sqlite3']

try:
	opts
except NameError:
	pass
else:
	props = [['enum', 'SQLITE_VER', 'Which SQLite version to use', sqlvers]]
	Return('props')

try:
	env
except NameError:
	pass
else:
	plugin	= {
		'type':			'log',
		'state':		'stable',
		'depends':		['@SQLITE_VER']
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
