
Import('*')

if 'env' in globals():
	plugin	= {
		'type':			'crypt',
		'state':		'unstable',
		# We use this fairly special syntax because only some versions of gpgme
		# require us having largefile support enabled. Thus, we first try to
		# link against it. If it fails, we enable largefile support and try once
		# again.
		'depends':		[['gpgme', 'largefile'], 'gpgme']
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
