# generate C files from XS

import glob

def CompileXSEmitter(target, source, env):
	target	= []
	for f in source:
		if str(f)[-3:] == '.xs':
			target.append(str(f).replace('.xs', '.c'))

	return target, source

def CompileXS(target, source, env, for_signature):
	map = dict(zip(target, source))
	ret = []
	for d,s in map.items():
		ret.append('xsubpp -typemap typemap "%s" > "%s"' % (s,d))

	return ret

xscomp = Builder(generator = CompileXS, emitter = CompileXSEmitter, suffix = '.c', src_suffix = '.xs')

Import('*')

penv['BUILDERS']['CompileXS'] = xscomp

perldirs = glob.glob('*/')
for dir in perldirs:
	penv.CompileXS(dir, glob.glob('%s*.xs' % dir))

# vim:ts=4:sts=4:sw=4:syntax=python
