
Import('*')

try:
	env	# stage 2
	plugin	= {
		'type':			'misc',
		'state':		'stable',
		'depends':		[],
#		'optdepends':	['inotify'] # XXX: use it ( ;
		}

	Return('plugin')
except NameError:
	pass

# vim:ts=4:sts=4:sw=4:syntax=python
