
Import('*')

try:
	env
except NameError:
	pass
else:
	plugin	= {
		'type':			'misc',
		'state':		'stable',
		'depends':		[],
#		'optdepends':	['inotify'] # XXX: use it ( ;
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
