
Import('*')

if 'defines' in globals():
	if 'openssl' in optdeps:
		defines['IRC_HAVE_OPENSSL'] = True

if 'env' in globals():
	plugin	= {
		'type':			'protocol',
		'state':		'stable',
		'depends':		[],
		'optdepends':	['openssl']
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
