
Import('*')

import glob

if 'env' in globals():
	plugin	= {
		'type':			'scripting',
		'state':		'stable',
		'depends':		['python']
		}

	Return('plugin')


if 'penv' in globals():
	penv.Install('%s/scripts/' % penv['DATADIR'], glob.glob('../../contrib/python/*.py'))

# vim:ts=4:sts=4:sw=4:syntax=python
