
Import('*')

import glob

try:
	env
except NameError:
	pass
else:
	plugin	= {
		'type':			'scripting',
		'state':		'stable',
		'depends':		['python']
		}

	Return('plugin')


try:
	penv
except NameError:
	pass
else:
	penv.Install('%s/scripts/' % penv['DATADIR'], glob.glob('../../contrib/python/*.py'))

# vim:ts=4:sts=4:sw=4:syntax=python
