
Import('*')

import glob

if ekg_compat:
	compatlibs = ['../compat/%scompat%s' % (benv['LIBPREFIX'], benv['LIBSUFFIX'])]
else:
	compatlibs = []

benv.Append(CPPPATH = ['..'])
benv.Program('ekg2-remote', glob.glob('*.c') + compatlibs)
benv.Install(benv['BINDIR'], '%sekg2-remote%s' % (benv['PROGPREFIX'], benv['PROGSUFFIX']))

# vim:ts=4:sts=4:sw=4:syntax=python
