
Import('*')

try:
	env	# stage 2
	plugin	= {
		'type':			'log',
		'state':		'stable',
		'depends':		[],
		'optdepends':	['zlib']
		}

	Return('plugin')
except NameError:
	pass

# vim:ts=4:sts=4:sw=4:syntax=python
