
Import('*')

try:
	env
except NameError:
	pass
else:
	plugin	= {
		'type':			'protocol',
		'state':		'unstable',
		'depends':		[],
		'optdepends':	['inotify']
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
