
Import('*')

if 'env' in globals():
	plugin	= {
		'type':			'ui',
		'state':		'unstable',
		'depends':		[],
		'extradist':	['xajax_0.2.4.js', 'ekg2.js', 'ekg2.css'],
		'noremote':		True
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
