
Import('*')

try:
	env	# stage 2
	plugin	= {
		'type':			'ui',
		'state':		'unstable',
		'depends':		[],
		'extradist':	['xajax_0.2.4.js', 'ekg2.js', 'ekg2.css']
		}

	Return('plugin')
except NameError:
	pass

# vim:ts=4:sts=4:sw=4:syntax=python
