#!/bin/sh
# skrypt uruchamiaj±cy ekg pod kontrol± valgrinda. przydatny tylko
# developerom. w snapshotach go nie ma.
valgrind --num-callers=10 --leak-check=yes --show-reachable=yes --trace-children=no -v --logfile-fd=3 ./ekg "$@" 3> ekg.log
