#!/bin/sh
# skrypt uruchamiaj±cy ekg pod kontrol± valgrinda. przydatny tylko
# developerom. w snapshotach go nie ma.
valgrind --num-callers=10 --leak-check=yes --show-reachable=yes --trace-children=no -v --logfile=ekg2.log ./ekg2 "$@"
