
Import('*')

try:
	env
except NameError:
	pass
else:
	plugin	= {
		'type':			'misc',
		'state':		'stable',
		'depends':		['ioctld'] # includes
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
