
Import('*')

try:
	env
except NameError:
	pass
else:
	plugin	= {
		'type':			'protocol',
		'state':		'stable',
		'depends':		['libgadu'],
		'optdepends':	['gif', 'jpeg'] # openssl & pthread are already contained in .pc
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
