
Import('*')

try:
	env	# stage 2
	plugin	= {
		'type':			'protocol',
		'state':		'stable',
		'depends':		['libgadu'],
		'optdepends':	['gif', 'jpeg'] # openssl & pthread are already contained in .pc
		}

	Return('plugin')
except NameError:
	pass

# vim:ts=4:sts=4:sw=4:syntax=python
