
Import('*')

try:
	env
except NameError:
	pass
else:
	plugin	= {
		'type':			'log',
		'state':		'experimental',
		'depends':		['pthread', 'oracle']
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
