
Import('*')

try:
	env
except NameError:
	pass
else:
	plugin	= {
		'type':			'ui',
		'state':		'experimental',
		'depends':		[],
		'optdepends':	[]
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
