
Import('*')

if 'env' in globals():
	plugin	= {
		'type':			'ui',
		'state':		'experimental',
		'depends':		[],
		'optdepends':	[],
		'noremote':		True
		}

	Return('plugin')

# vim:ts=4:sts=4:sw=4:syntax=python
